Pani-Geuni/rence-Boot

- pom.xml
- src/main/java/com/rence/backoffice/controller/BackOfficeController.java
- src/main/java/com/rence/backoffice/model/AuthVO.java
- src/main/java/com/rence/backoffice/model/BackOfficeOperatingTimeVO.java
- src/main/java/com/rence/backoffice/model/BackOfficeOperatingTimeVO_datetype.java
- src/main/java/com/rence/backoffice/model/BackOfficeVO.java
- src/main/java/com/rence/backoffice/model/EmailVO.java
- src/main/java/com/rence/backoffice/service/AuthRepository.java
- src/main/java/com/rence/backoffice/service/BackOfficeFileService.java
- src/main/java/com/rence/backoffice/service/BackOfficeOperatingTimeRepository.java
- src/main/java/com/rence/backoffice/service/BackOfficeRepository.java
- src/main/java/com/rence/backoffice/service/BackOfficeSendEmail.java
- src/main/java/com/rence/backoffice/service/BackOfficeService.java
- src/main/java/com/rence/backoffice/service/CustomDateFormatter.java
- src/main/java/com/rence/backoffice/service/OperatingTime.java
- src/main/resources/application.properties
> [feat] BackOffice boot 세팅

- src/main/java/com/rence/backoffice/service/BackOfficeRepository.java
- src/main/java/com/rence/master/controller/MasterController.java
- src/main/java/com/rence/master/model/MasterRepository.java
- src/main/java/com/rence/master/service/MasterSendEmail.java
- src/main/java/com/rence/master/service/MasterService.java
> [feat] Master 세팅

- pom.xml
- src/main/java/com/rence/backoffice/service/SecurityConfig.java
> [feat] pom.xml security 추가

- src/main/java/com/rence/backoffice/repository/AuthRepository.java
- src/main/java/com/rence/backoffice/repository/BackOfficeOperatingTimeRepository.java
- src/main/java/com/rence/backoffice/repository/BackOfficeRepository.java
- src/main/java/com/rence/backoffice/service/BackOfficeService.java
- src/main/java/com/rence/master/repository/MasterRepository.java
- src/main/java/com/rence/master/service/MasterService.java
> [feat] BsckOffice, Master repository package 분리

- src/main/java/com/rence/backoffice/service/SecurityConfig.java
> [feat] security 예외 파일 수정

- src/main/java/com/rence/config/MultipleSecurityConfiguration.java
> [feat] Office Security 수정

- src/main/java/com/rence/config/MultipleSecurityConfiguration.java
> [feat] User(Office) Security 수정

- src/main/java/com/rence/config/MultipleSecurityConfiguration.java
> [feat] User Security 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/ReserveEntity.java
- src/main/java/com/rence/dashboard/model/ReserveSummaryVO.java
- src/main/java/com/rence/dashboard/repository/ReserveRepository.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
> [feat] DashBoard 시작..

- src/main/java/com/rence/dashboard/model/BOPaymentVO.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/dashboard/model/ReserveVIEW.java
- src/main/java/com/rence/dashboard/repository/ReserveRepository.java
> [feat] view list 수정 중

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
> [feat] DashBoard persistence 막음

- src/main/java/com/rence/backoffice/repository/BackOfficeRepository.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
> [feat] 비밀번호 비교 암호화 수정

- src/main/java/com/rence/backoffice/controller/BackOfficeController.java
- src/main/java/com/rence/backoffice/repository/BackOfficeFAO.java
- src/main/java/com/rence/backoffice/repository/BackOfficeFAOImpl.java
- src/main/java/com/rence/backoffice/service/BackOfficeFileService.java
> [feat] image file dao daoimpl 생성

- src/main/java/com/rence/backoffice/repository/BackOfficeFAO.java
- src/main/java/com/rence/backoffice/repository/BackOfficeFAOImpl.java
- src/main/java/com/rence/backoffice/service/BackOfficeFileService.java
> [feat] 작성자 추가

- src/main/java/com/rence/backoffice/controller/BackOfficeController.java
- src/main/java/com/rence/backoffice/repository/AuthRepository.java
- src/main/java/com/rence/backoffice/repository/BackOfficeFAOImpl.java
- src/main/java/com/rence/backoffice/repository/BackOfficeOperatingTimeRepository.java
- src/main/java/com/rence/backoffice/repository/BackOfficeRepository.java
- src/main/java/com/rence/backoffice/service/BackOfficeService.java
> [feat] image file upload 완료

- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
> [refactor] 정산 금액 수정

- src/main/java/com/rence/master/controller/MasterController.java
> [feat] Master 호스트 상세보기

- src/main/java/com/rence/config/MultipleSecurityConfiguration.java
- src/main/resources/static/JS/backoffice/host_popup.js
- src/main/resources/templates/thymeleaf/layouts/backoffice/layout_backoffice.html
> [feat] BackOffice login

- src/main/resources/static/CSS/backoffice/host-login.css
- src/main/resources/templates/thymeleaf/layouts/backoffice/layout_backoffice.html
> [refactor] 호스트 로그인 이미지 변경

- src/main/java/com/rence/backoffice/repository/BackOfficeRepository.java
- src/main/java/com/rence/config/MultipleSecurityConfiguration.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
> [feat] DashBord 환경 설정 - 정보 변경 진행 중

- src/main/java/com/rence/backoffice/repository/BackOfficeOperatingTimeRepository.java
- src/main/java/com/rence/backoffice/repository/BackOfficeRepository.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/repository/RoomSummaryRepository.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
- src/main/java/com/rence/master/controller/MasterController.java
> [feat] BackOffice update 구현 중

- src/main/resources/templates/thymeleaf/html/office/my_page/my_page.html
마이페이지 내에서 src 지정이 아닌 layout에서 지정으로 변경
> [refactor] 마이페이지 내에서 src 지정 위치 변경

- src/main/java/com/rence/AOPConfig.java
- src/main/java/com/rence/AutoAspect.java
- src/main/java/com/rence/backoffice/repository/AuthRepository.java
- src/main/java/com/rence/backoffice/service/BackOfficeService.java
- src/main/java/com/rence/config/AuthorityChangeFilter.java
- src/main/java/com/rence/config/MultipleSecurityConfiguration.java
> [feat] 인증번호 유효시간

- src/main/resources/static/JS/backoffice/host_popup.js
> [refactor] 호스트팝업.js 서블릿 주소 변경

- src/main/java/com/rence/backoffice/controller/BackOfficeController.java
- src/main/java/com/rence/backoffice/service/BackOfficeService.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/repository/RoomSummaryRepository.java
- src/main/java/com/rence/master/service/MasterSendEmail.java
- src/main/resources/templates/thymeleaf/html/backoffice/landing/setting_pw.html
> [feat] DashBoard main  entity 타입 수정

- src/main/java/com/rence/backoffice/model/BackOfficeVO.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/resources/application.properties
> [feat] 문의 수정 중

- src/main/java/com/rence/backoffice/repository/BackOfficeRepository.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/dashboard/repository/ReserveAutoUpdateRepository.java
- src/main/java/com/rence/dashboard/repository/SalesSettlementRepository.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
> [feat] 예약 취소 시, 예약 상태 변경

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/dashboard/repository/SalesSettlementRepository.java
> [feat] backoffice 오타 수정

- src/main/java/com/rence/config/MultipleSecurityConfiguration.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/dashboard/repository/SalesSettlementRepository.java
- src/main/resources/application.properties
- src/main/resources/static/CSS/dash-board/dash-commons.css
- src/main/resources/static/JS/backoffice/host_popup.js
> [feat] 백오피스 시큐리티 토큰 삭제

- src/main/java/com/rence/AutoAspect.java
- src/main/java/com/rence/backoffice/service/BackOfficeSendEmail.java
- src/main/java/com/rence/dashboard/service/DashboardSendEmail.java
- src/main/java/com/rence/master/service/MasterSendEmail.java
- src/main/resources/application.properties
e-mail 내용 수정, 예약 상태 업데이트 aop 주석 해제
> [feat] e-mail 내용 수정, 예약 상태 업데이트 aop 주석 해제

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/dashboard/model/SalesSettlementViewVO.java
- src/main/java/com/rence/dashboard/repository/SalesSettlementRepository.java
- src/main/resources/templates/thymeleaf/html/backoffice/dashboard/update_host.html
> [feat] 일정 휴무, 브레이크 날짜/시간 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/ScheduleListView.java
- src/main/java/com/rence/dashboard/repository/ScheduleListRepository.java
- src/main/java/com/rence/dashboard/repository/ScheduleRepository.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
일정 리스트 쿼리 수정, 휴무 일정 리스트, 휴무 취소 구현
> [feat] 일정 리스트 쿼리 수정, 휴무 일정 리스트, 휴무 취소 구현

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
> [feat] reservation controller 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/DashBoardDAO.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/dashboard/repository/ReservationRepository.java
- src/main/java/com/rence/dashboard/repository/SalesSettlementRepository.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
> [feat] 예약자 페이징

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/DashBoardDAO.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/dashboard/model/ReserveListView.java
- src/main/java/com/rence/dashboard/repository/ReserveRepository.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
> [feat] 예약 관리(리스트,검색) 페이징

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
> [feat] 예약 관리 페이징 페이지 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
> [feat] 일정관리 리스트 페이징 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
> [feat] 일정관리 페이징 수정

- src/main/java/com/rence/backoffice/model/BackOfficeOperatingTimeVO.java
- src/main/java/com/rence/backoffice/repository/BackOfficeOperatingTimeSelectRepository.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
- src/main/resources/static/CSS/common/custom-timepicker.css
- src/main/resources/static/CSS/dash-board/jquery-ui-timepicker.css
- src/main/resources/static/CSS/dash-board/jquery-ui.css
- src/main/resources/static/CSS/office/jquery-ui.css
- src/main/resources/static/JS/backoffice/host_update.js
- src/main/resources/templates/thymeleaf/html/backoffice/dashboard/update_host.html
> [feat] 호스트 정보 변경 진행 중, 타임피커 css 수정

- src/main/resources/static/JS/backoffice/schedule.js
> [feat] 일정 신청 진행 중

- src/main/resources/static/CSS/backoffice/host-insert.css
- src/main/resources/static/CSS/dash-board/dash-host-update.css
- src/main/resources/static/JS/backoffice/schedule.js
- src/main/resources/templates/thymeleaf/html/backoffice/dashboard/update_host.html
> [feat] 호스트 정보 수정 글자 수 제한

- src/main/java/com/rence/dashboard/model/BOPaymentVO.java
> [feat] 예약 취소 에러 수정

- src/main/java/com/rence/backoffice/controller/BackOfficeController.java
- src/main/java/com/rence/backoffice/repository/AuthRepository.java
- src/main/java/com/rence/backoffice/service/BackOfficeService.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
> [feat] 이메일 인증 재 전송 결과 값

- src/main/java/com/rence/AutoAspect.java
> [feat] aop email 삭제 시간 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/resources/static/JS/backoffice/schedule.js
> [feat] 일정 신청 후, 리스트 정렬

- src/main/java/com/rence/AutoAspect.java
- src/main/java/com/rence/backoffice/repository/AuthRepository.java
- src/main/java/com/rence/backoffice/service/BackOfficeService.java
> [refactor] 이메일 유효 시간 초과 후 삭제 코드 수정

- src/main/resources/static/JS/office/user_popup.js
- 창닫기 버튼 클릭 시 clearInterval()
- 인증번호 인증 완료 시 버튼 텍스트 수정
> [refactor] 회원가입 팝업 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/BOPaymentVO.java
- src/main/java/com/rence/dashboard/service/HostPaymentCancelService.java
> [feat] 호스트 결제 취소 구현

- src/main/resources/templates/thymeleaf/html/office/space_detail/space_detail_introduce.html
- src/main/resources/templates/thymeleaf/layouts/office/layout_base.html
쿠키 파일을 못읽어서 홈페이지로 연결시켜 쿠키 함수 적용시킴
> [refactor] 오피스 공간 상세 헤더관련버그해결

- src/main/java/com/rence/backoffice/controller/BackOfficeController.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/security/BackOfiiceSecurityConfig.java
- src/main/resources/templates/thymeleaf/html/backoffice/dashboard/update_host.html
> [refactor] 업체 정보 수정, 일정 관리 수정

- src/main/java/com/rence/dashboard/repository/CommentQListRepository.java
> [refactor] 문의 정렬 날짜 내림차순

- src/main/java/com/rence/backoffice/repository/BackOfficeRepository.java
- src/main/resources/static/JS/backoffice/host_update.js
> [refactor] 업체 정보 변경 시, 타입 변경 불가 구현

- src/main/java/com/rence/dashboard/repository/ScheduleRepository.java
> [refactor] 휴무 일정 현재 달만 출력으로 수정

- src/main/java/com/rence/backoffice/controller/BackOfficeController.java
- src/main/java/com/rence/backoffice/repository/BackOfficeRepository.java
- src/main/java/com/rence/backoffice/service/BackOfficeSendEmail.java
- src/main/java/com/rence/security/BackOfiiceSecurityConfig.java
> [refactor] 비빌번호 찾기 시큐리티 제한 해제

- src/main/resources/static/CSS/office/list-page.css
- src/main/resources/static/JS/backoffice/host_header.js
- src/main/resources/templates/thymeleaf/layouts/backoffice/layout_backoffice.html
- src/main/resources/templates/thymeleaf/layouts/office/layout_base.html
> [refactor] 대시보드 이동 조건 수정

- src/main/java/com/rence/dashboard/repository/CommentQListRepository.java
> [refactor] 문의 리스트 출력 정렬 수정

- src/main/java/com/rence/office/repo/OfficeInfoRepository.java
- src/main/resources/static/CSS/dash-board/dash-space-list.css
- src/main/resources/static/CSS/office/space-detail-introduce-office.css
- src/main/resources/static/CSS/office/space-detail-introduce.css
- src/main/resources/templates/thymeleaf/html/office/space_detail/space_detail_introduce_office.html
1. 불필요한 코드 제거
2. sysdate -> current_date
3. ::after 제거 후 서버에서 받기로
4. 오피스 문의 탭 수정
5. 공간 소개 - 공간 설명 띄어쓰기 반영
> [refactor] QA에서 발견한 부분 수정중

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
> [refactor] 공간 단위 수정

- src/main/resources/templates/thymeleaf/html/backoffice/dashboard/room.html
> [refactor] 공간 요금 단위 수정 중

- src/main/resources/static/JS/backoffice/schedule.js
> [refactor] 일정 설정 작성자, 주석 추가

- src/main/java/com/rence/backoffice/controller/BackOfficeController.java
> [refactor] 비밀번호 변경 에러 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/ScheduleEntity.java
- src/main/java/com/rence/dashboard/repository/RoomInsertRepository.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
> [refactor] 휴무 일정 출력 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/ScheduleEntity.java
> [refactor] 휴무 일정 출력 vo 수정

- src/main/resources/templates/thymeleaf/html/office/my_page/reserve_list.html
> [refactor] 예약 리스트 내 텍스트 변경

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/master/controller/MasterController.java
- src/main/resources/static/JS/backoffice/host_update.js
> [refactor] master - 백오피스 상세 보기 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/resources/static/JS/backoffice/host_update.js
- src/main/resources/static/JS/backoffice/schedule.js
- src/main/resources/templates/thymeleaf/layouts/backoffice/layout_dashboard.html
> [refactor] 업체 정보 수정 tag 에러 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/dashboard/repository/SalesMileageRepository.java
- src/main/java/com/rence/dashboard/repository/SalesSettlementRepository.java
> [refactor] 정산 상태 변경 로직 수정

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
> [refactor] 예약 관리 페이징 수정 중

- src/main/java/com/rence/AutoAspect.java
- src/main/java/com/rence/dashboard/repository/ReserveAutoUpdateRepository.java
- src/main/java/com/rence/dashboard/repository/ReserveRepository.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
> [feat] 예약 false 30분 뒤 삭제

- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
> [refactor] 휴무, 브레이크 타임 종료 시간 수정

- src/main/java/com/rence/AutoAspect.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
> [refactor] 예약 상태 업데이트 메소드 명'_rsu' 추가

- src/main/java/com/rence/AutoAspect.java
- src/main/java/com/rence/dashboard/repository/ReserveAutoUpdateRepository.java
- src/main/java/com/rence/dashboard/service/DashboardService.java
> [refactor] 예약 상태 false 자동 삭제 쿼리 수정

- src/main/java/com/rence/AutoAspect.java
> [refactor] 예약 상태 false 삭제 부분 수정

- src/main/java/com/rence/backoffice/controller/BackOfficeController.java
- src/main/java/com/rence/backoffice/model/AuthVO.java
- src/main/java/com/rence/backoffice/model/BackOfficeListVO.java
- src/main/java/com/rence/backoffice/model/BackOfficeVO.java
- src/main/java/com/rence/backoffice/model/EmailVO.java
- src/main/java/com/rence/dashboard/controller/DashBoardController.java
- src/main/java/com/rence/dashboard/model/DashBoardDAOImpl.java
- src/main/java/com/rence/dashboard/model/ReserveListView.java
- src/main/java/com/rence/dashboard/model/ReviewListView.java
- src/main/java/com/rence/dashboard/repository/ScheduleRepository.java
- src/main/java/com/rence/master/controller/MasterController.java
> [refactor] 코드 정리
